language: node_js
node_js:
- '4'
- node
deploy:
  provider: npm
  email: wwigham@gmail.com
  api_key:
    secure: RsNs/Esw3ozBCLvt976sgsY++cw1a493gH1dCJvxESRmj0XHtQqdjQDVmFgbNmrZ3DosawUrSUScWPiKm5+gmxGxaz9P/niM+JPx6+mv7jBw4XMRAJcFLa0BlZwRgkB5xcfCM/ZrS7oLvNazz/vGalaqgskjCRa239tsvz75UrQ=
  on:
    tags: true
    repo: weswigham/metalsmith-metallic
